export const STRINGS = {
  nl: {
    topPill: "De Haagse Hogeschool",
    heroTitle: "T.I.S. Bedrijvendag",
    heroSubtitle:
      "Ontmoet toonaangevende bedrijven, ontdek kansen en zet de eerste stap naar jouw carrière.",
    dateLabel: "Datum",
    dateValue: "05/03/2026",
    timeLabel: "Tijd",
    timeValue: "10:00 - 17:00",
    locationLabel: "Locatie",
    locationValue: "HHS Delft",
    locationAddress: "Rotterdamseweg 137, 2628 AL Delft",
    ctaDiscover: "Ontdek bedrijven",
    companiesKicker: "ONZE PARTNERS",
    companiesTitle: "Deelnemende bedrijven",
    companiesSubtitle:
      "Beweeg over een bedrijf om meer te leren over hun missie en beschikbare mogelijkheden.",
    aboutKicker: "WAT JE KUNT VERWACHTEN",
    aboutTitleA: "Jouw toegangspoort tot",
    aboutTitleB: "professioneel succes",
    aboutBody:
      "Career Day 2026 brengt de slimste studenten en toonaangevende bedrijven samen. Of je nu op zoek bent naar een stage, een startersfunctie of je carrièrepad wilt verkennen: dit is jouw kans om waardevolle connecties te leggen.",
    statsCompanies: "Bedrijven",
    statsStudents: "Studenten",
    statsOpportunities: "Kansen",
    footerCtaTitle: "Klaar om jouw toekomst vorm te geven?",
    footerCtaBody:
      "Kom langs, ontmoet bedrijven en verenigingen, en breid je netwerk uit.",
    footerSponsoredBy: "Website gesponsord door Galerie B",
    footerAboutTitle: "Over",
    footerAboutBody:
      "De Haagse Hogeschool verbindt onderwijs en werkveld en helpt studenten klaar te stomen voor de uitdagingen van morgen.",
    footerLinksTitle: "Snelle links",
    footerLinkAbout: "Over het event",
    footerLinkCompanies: "Bedrijven",
    footerLinkSchedule: "Programma",
    footerLinkFaq: "FAQ",
    footerContactTitle: "Contact",
    footerPrivacy: "Privacybeleid",
    footerTerms: "Gebruiksvoorwaarden",
    visitWebsite: "Website bezoeken",
    industry: "Sector",
    employees: "Medewerkers",
    region: "Regio",
    opportunities: "Mogelijkheden",
    associationsKicker: "ORGANISERENDE VERENIGINGEN",
    associationsTitle: "Studieverenigingen",
    associationsSubtitle: "Klik op een vereniging om naar de website te gaan.",
    tbd: "TBD"
  },
  en: {
    topPill: "The Hague University of Applied Sciences",
    heroTitle: "T.I.S. Career Day",
    heroSubtitle:
      "Connect with leading companies, explore opportunities, and take the first step towards your career.",
    dateLabel: "Date",
    dateValue: "March 5, 2026",
    timeLabel: "Time",
    timeValue: "10:00 - 17:00",
    locationLabel: "Location",
    locationValue: "THUAS Delft",
    locationAddress: "Rotterdamseweg 137, 2628 AL Delft",
    ctaDiscover: "Discover Companies",
    companiesKicker: "MEET OUR PARTNERS",
    companiesTitle: "Participating Companies",
    companiesSubtitle:
      "Hover over each company to learn more about their mission and available roles.",
    aboutKicker: "WHAT TO EXPECT",
    aboutTitleA: "Your gateway to",
    aboutTitleB: "professional success",
    aboutBody:
      "Career Day 2026 brings together top students and leading companies. Whether you're seeking an internship, a graduate role, or exploring career paths, this is your chance to build meaningful connections.",
    statsCompanies: "Companies",
    statsStudents: "Students",
    statsOpportunities: "Opportunities",
    footerCtaTitle: "Ready to shape your future?",
    footerCtaBody:
      "Meet companies and associations, ask questions, and grow your network.",
    footerSponsoredBy: "Website sponsored by Galerie B",
    footerAboutTitle: "About",
    footerAboutBody:
      "The Hague University of Applied Sciences prepares students through practical education and strong industry connections.",
    footerLinksTitle: "Quick Links",
    footerLinkAbout: "About the Event",
    footerLinkCompanies: "Companies",
    footerLinkSchedule: "Schedule",
    footerLinkFaq: "FAQ",
    footerContactTitle: "Contact",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    visitWebsite: "Visit Website",
    industry: "Industry",
    employees: "Employees",
    region: "Region",
    opportunities: "Opportunities",
    associationsKicker: "ORGANISING ASSOCIATIONS",
    associationsTitle: "Study Associations",
    associationsSubtitle: "Click on an association to visit its website.",
    tbd: "TBD"
  }
};
